[project]
name = "layoutnotification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "auto-py-to-exe>=2.50.1",
    "customtkinter>=5.2.2",
    "pillow>=12.2.0",
    "pystray>=0.19.5",
    "pywin32>=311",
]

[tool.pyright]

venvPath = "."
venv = ".venv"
